---
title: ""
format: html
toc: false
---

::: {style="display: flex; justify-content: flex-end; gap: 10px;"}
[Download Resume (PDF)](/static/resume/resume.pdf){.btn .btn-primary}

[Download Resume (DOCX)](/static/resume/resume.docx){.btn .btn-secondary}
:::



# Jessica Danielle Geiger

#### **Data Scientist | Drug Discovery & Machine Learning | Life Sciences**

(831)-801-9453  |  daniellegeiger99@gmail.com  | 
GitHub: github.com/danigeiger | LinkedIn: www.linkedin.com/in/jessica-d-geiger

#### Data Scientist | Drug Discovery & Machine Learning (Life Sciences)

Master’s-trained Data Scientist with a background in human physiology and experience in pharmaceutical R&D. Specialized in applying machine learning to biological and chemical data, including predictive modeling for drug discovery. Experienced in building end-to-end data pipelines, feature engineering molecular data, and deploying models via interactive applications.


#### TECHNICAL SKILLS

**Programming & Data**  
- Python, R, SQL  
- Pandas, NumPy  
- Git/GitHub  
- scikit-learn, TensorFlow  

**Machine Learning & Statistics**
- Exploratory Data Analysis (EDA)  
- Statistical analysis & data validation  
- Data preprocessing & feature engineering  
- Regression & classification models  
- Ensemble methods  
- Feature selection & PCA  

**Visualization Tools**  
- Streamlit  
- Excel  
- Quarto  
- matplotlib

**Cloud Tools**  
- AWS EC2  
- AWS S3  
- AWS Athena

#### EXPERIENCE

**Aromas-San Juan Unified School District**  
*Substitute Teacher (Aug 2023 – Present)*

- Designed and delivered curriculum tailored to diverse learning levels, ensuring comprehension of key concepts across subjects  
- Assessed student understanding through formative evaluations and adapted instruction to improve learning outcomes  
- Collaborated with faculty and staff to maintain continuity of instruction and foster a positive classroom environment  
- Developed strong organizational, classroom management, and problem-solving skills in fast-paced settings  

---

**AstraZeneca**  
*Associate, R&D (Sep 2022 – Jun 2023)*

- Supported biologic drug formulation in a cGMP environment, contributing to batch production for clinical trials  
- Maintained and analyzed batch data, process parameters, and quality metrics to ensure consistency, regulatory compliance, and reproducibility  
- Monitored spray-drying operations, identifying relationships between process variables and product outcomes to improve formulation performance and stability  
- Collaborated with directors and process engineers to troubleshoot variability and meet target specifications, enabling development of a safe and effective clinical formulation  

#### PROJECTS
CGRP Drug Discovery Capstone Project (Github)
Developed an end-to-end machine learning pipeline to predict small molecule inhibitory activity (IC50) against the CGRP receptor using bioactivity data from ChEMBL
Engineered 800+ molecular fingerprint features and applied variance threshold feature selection and PCA
Built a reproducible preprocessing pipeline and deployed a Streamlit application for real-time predictions

#### EDUCATION & CERTIFICATIONS
AWS Certified Cloud Practitioner 
M.S. Data Science – Eastern University (2025)
B.S. Human Physiology (Minor: Biochemistry) – University of Oregon (2020)

